In [58]:
class SimpleLinearRegression:
    
    def __init__(self):
        self.m = None
        self.c = None
    
    def fit(self, X_train, y_train):
        num = 0
        den = 0
        
        for i in range(len(X_train)):
            num = num + ((X_train[i] - X_train.mean())*(y_train[i] - y_train.mean()))
            den = den + ((X_train[i] - X_train.mean()) * (X_train[i] - X_train.mean()))
        
        self.m = num/den
        
        self.c = y_train.mean() - (self.m * X_train.mean())
        
        print(self.m, self.c)
    
    def predict(self, X_test):
        y = self.m * X_test + self.c
        print(y)

In [2]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("sample_data.csv")

In [4]:
df.head()

Experience Years  Salary
0               1.1   39343
1               1.2   42774
2               1.3   46205
3               1.5   37731
4               2.0   43525

In [5]:
from sklearn.model_selection import train_test_split

In [23]:
X = df.iloc[:,0].values

In [37]:
y = df.iloc[:,1].values

In [38]:
y

array([ 39343,  42774,  46205,  37731,  43525,  39891,  48266,  56642,
        60150,  54445,  64445,  60000,  57189,  60200,  63218,  55794,
        56957,  57081,  59095,  61111,  64500,  67938,  66029,  83088,
        82200,  81363,  93940,  91000,  90000,  91738,  98273, 101302,
       113812, 111620, 109431, 105582, 116969, 112635, 122391, 121872],
      dtype=int64)

In [39]:
X

array([ 1.1,  1.2,  1.3,  1.5,  2. ,  2.2,  2.5,  2.9,  3. ,  3.2,  3.2,
        3.5,  3.7,  3.8,  3.9,  4. ,  4. ,  4.1,  4.3,  4.5,  4.7,  4.9,
        5.1,  5.3,  5.5,  5.9,  6. ,  6.2,  6.5,  6.8,  7.1,  7.9,  8.2,
        8.5,  8.7,  9. ,  9.5,  9.6, 10.3, 10.5])

In [42]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [59]:
lr = SimpleLinearRegression()

In [60]:
lr.fit(X_train,y_train)

9629.895616355 24469.05453811407


In [61]:
X_train.shape

(32,)

In [62]:
y_train.shape

(32,)

In [63]:
X_test

array([6.2, 3.2, 3.9, 1.1, 1.3, 7.1, 3.8, 9.5])

In [64]:
y_test

array([ 91000,  54445,  63218,  39343,  46205,  98273,  60200, 116969],
      dtype=int64)

In [65]:
lr.predict(6.2)

84174.40735951507


In [66]:
X_test[0]

6.2